// Generated by generate_tdr_upload_script.py; do not edit.
// Paste this entire file into DevTools Console on the NTU upload page.
(async () => {
  const DATA = __TDR_DATA__;

  function get(selector) {
    const element = document.querySelector(selector);
    if (!element) {
      console.error(`❌ 找不到欄位：${selector}`);
      return null;
    }
    return element;
  }

  function announceInput(element) {
    element.dispatchEvent(new Event("input", { bubbles: true }));
    element.dispatchEvent(new Event("change", { bubbles: true }));
  }

  function setValue(selector, value) {
    const element = get(selector);
    if (!element) return;
    element.value = value ?? "";
    announceInput(element);
    console.log(`✅ ${selector}`);
  }

  // Select fields accept either the displayed option text or its value.
  function setSelect(selector, value) {
    const element = get(selector);
    if (!element) return;

    const wanted = String(value);
    const option = [...element.options].find(
      item => item.value === wanted || item.textContent.trim() === wanted
    );
    if (!option) {
      console.error(
        `❌ ${selector} 找不到選項 "${value}"`,
        [...element.options].map(item => ({
          text: item.textContent.trim(),
          value: item.value
        }))
      );
      return;
    }

    element.value = option.value;
    announceInput(element);
    console.log(`✅ ${selector} → ${option.textContent.trim()}`);
  }

  function setKeywords(name, values) {
    values = (values ?? []).map(value => String(value).trim()).filter(Boolean);

    const layouts = [...document.querySelectorAll(`.${name}_layout`)];
    layouts.slice(1).forEach(layout => layout.remove());

    const first = document.querySelector(`input[name="${name}"]`);
    if (!first) {
      console.error(`❌ 找不到 ${name}`);
      return;
    }

    first.value = "";
    if (values.length === 0) return;
    first.value = values[0];
    announceInput(first);

    for (let index = 1; index < values.length; ++index) {
      const plusButtons = document.querySelectorAll(`.${name}_plus`);
      const lastPlus = plusButtons[plusButtons.length - 1];
      if (!lastPlus) {
        console.error(`❌ 找不到 ${name} 的 + 按鈕`);
        break;
      }

      // Use the upload page's own function to add a correctly named field.
      KeywordPlus(lastPlus);
      const inputs = document.querySelectorAll(`input[name="${name}"]`);
      const input = inputs[inputs.length - 1];
      input.value = values[index];
      announceInput(input);
    }
    console.log(`✅ ${name}：${values.length} 個關鍵字`);
  }

  // 口試委員名單。TDR 的委員欄位長什麼樣子沒有公開文件可查，這個模板也就不去
  // 猜它的選擇器——猜錯若剛好命中別的欄位，會安靜地寫壞資料。因此這裡只把名單
  // 整理成表格印在 Console，供手動輸入。
  //
  // 若你已經知道正確的選擇器，改寫下面的迴圈即可，setValue 與 setSelect 都可直接使用。
  //
  // The committee section's field names are not documented anywhere public, and
  // guessing a selector that happens to match some other field would corrupt
  // data silently. So this prints the list for manual entry instead. If you know
  // the real selectors, replace the loop below; setValue and setSelect are
  // available.
  function showCommittee(members) {
    if (!members || members.length === 0) {
      console.warn("⚠️ 沒有口試委員資料");
      return;
    }
    console.log(`📋 口試委員 ${members.length} 位，請手動填入：`);
    console.table(
      members.map((member, index) => ({
        "#": index + 1,
        身分: member.title,
        姓名: member.nameZh,
        Name: member.nameEn,
        Email: member.email,
        ORCID: member.orcid || "",
      }))
    );
  }

  console.log("🚀 開始填寫 NTU 論文資料");

  setSelect('select[name="pappertype"]', "學術論文");
  setValue("#tittle", DATA.titleZh);
  setValue("#tittle_en", DATA.titleEn);
  setSelect('select[name="dept_res"]', DATA.department);
  setSelect('select[name="grad_year"]', DATA.graduationYear);
  setSelect('select[name="term"]', DATA.semester);
  setSelect('select[name="pub_year"]', DATA.publicationYear);

  setValue("#author", DATA.authorZh);
  setValue("#author_en", DATA.authorEn);
  setValue('input[name="ORCID"]', DATA.orcid);
  setValue("#email", DATA.email);
  setValue("#email2", DATA.email2);

  setSelect('select[name="language"]', DATA.language);
  setValue("#final_date", DATA.defenseDate);
  setValue("#pages", DATA.pages);

  setKeywords("keyword_c", DATA.keywordsZh);
  setKeywords("keyword_e", DATA.keywordsEn);

  setValue("#ac", DATA.abstractZh);
  setValue("#ae", DATA.abstractEn);
  setValue("#content", DATA.tableOfContents);
  setValue("#refer", DATA.references);
  setValue("#note", DATA.note);

  showCommittee(DATA.committee);

  window.scrollTo({ top: 0, behavior: "smooth" });

  console.log("================================");
  console.log("✅ 所有欄位填寫完成");
  console.log("⚠️ 口試委員需依上表手動填入");
  console.log("⚠️ 尚未按「暫存」或「下一步」");
  console.log("⚠️ 請檢查內容後自行按按鈕");
  console.log("================================");
})();
