// Generated by generate_tdr_upload_script.py; do not edit.
// Paste this entire file into DevTools Console on the NTU upload page.
// The same file serves both steps: it detects whether 「輸入論文資料」
// (Submit.jsp) or 「設定口試委員名單」(TempAdvisor.jsp) is open.
(async () => {
  const DATA = __TDR_DATA__;

  function get(selector, root = document) {
    const element = root.querySelector(selector);
    if (!element) {
      console.error(`❌ 找不到欄位：${selector}`);
      return null;
    }
    return element;
  }

  function announceInput(element) {
    element.dispatchEvent(new Event("input", { bubbles: true }));
    element.dispatchEvent(new Event("change", { bubbles: true }));
  }

  function setValue(selector, value, { root = document, label = selector } = {}) {
    const element = get(selector, root);
    if (!element) return;
    element.value = value ?? "";
    announceInput(element);
    console.log(`✅ ${label}`);
  }

  // Select fields accept either the displayed option text or its value.
  function setSelect(selector, value, { root = document, label = selector } = {}) {
    const element = get(selector, root);
    if (!element) return;

    const wanted = String(value);
    const option = [...element.options].find(
      item => item.value === wanted || item.textContent.trim() === wanted
    );
    if (!option) {
      console.error(
        `❌ ${label} 找不到選項 "${value}"`,
        [...element.options].map(item => ({
          text: item.textContent.trim(),
          value: item.value
        }))
      );
      return;
    }

    element.value = option.value;
    announceInput(element);
    console.log(`✅ ${label} → ${option.textContent.trim()}`);
  }

  function setKeywords(name, values) {
    values = (values ?? []).map(value => String(value).trim()).filter(Boolean);

    const layouts = [...document.querySelectorAll(`.${name}_layout`)];
    layouts.slice(1).forEach(layout => layout.remove());

    const first = document.querySelector(`input[name="${name}"]`);
    if (!first) {
      console.error(`❌ 找不到 ${name}`);
      return;
    }

    first.value = "";
    if (values.length === 0) return;
    first.value = values[0];
    announceInput(first);

    for (let index = 1; index < values.length; ++index) {
      const plusButtons = document.querySelectorAll(`.${name}_plus`);
      const lastPlus = plusButtons[plusButtons.length - 1];
      if (!lastPlus) {
        console.error(`❌ 找不到 ${name} 的 + 按鈕`);
        break;
      }

      // Use the upload page's own function to add a correctly named field.
      KeywordPlus(lastPlus);
      const inputs = document.querySelectorAll(`input[name="${name}"]`);
      const input = inputs[inputs.length - 1];
      input.value = values[index];
      announceInput(input);
    }
    console.log(`✅ ${name}：${values.length} 個關鍵字`);
  }

  function fillThesisPage() {
    setSelect('select[name="pappertype"]', "學術論文");
    setValue("#tittle", DATA.titleZh);
    setValue("#tittle_en", DATA.titleEn);
    setSelect('select[name="dept_res"]', DATA.department);
    setSelect('select[name="grad_year"]', DATA.graduationYear);
    setSelect('select[name="term"]', DATA.semester);
    setSelect('select[name="pub_year"]', DATA.publicationYear);

    setValue("#author", DATA.authorZh);
    setValue("#author_en", DATA.authorEn);
    setValue('input[name="ORCID"]', DATA.orcid);
    setValue("#email", DATA.email);
    setValue("#email2", DATA.email2);

    setSelect('select[name="language"]', DATA.language);
    setValue("#final_date", DATA.defenseDate);
    setValue("#pages", DATA.pages);

    setKeywords("keyword_c", DATA.keywordsZh);
    setKeywords("keyword_e", DATA.keywordsEn);

    setValue("#ac", DATA.abstractZh);
    setValue("#ae", DATA.abstractEn);
    setValue("#content", DATA.tableOfContents);
    setValue("#refer", DATA.references);
    setValue("#note", DATA.note);
    return true;
  }

  // 口試委員名單。下面的選擇器是照 TDR「設定口試委員名單」頁面的原始碼寫的，
  // 不是猜的；欄位名稱在同一個區塊內重複，所以每個欄位都限定在自己的
  // .advisor_layout 裡尋找，不能用 document.querySelector 或 id。
  //
  // The selectors below come from the markup of TDR's 「設定口試委員名單」page
  // rather than from guesswork. The field names (and ids) repeat once per
  // member, so every lookup is scoped to its own .advisor_layout block instead
  // of going through document.querySelector or an id.
  function fillCommitteePage() {
    const form = get('form[name="StuTempAdvisorForm"]');
    if (!form) return false;

    const members = DATA.committee ?? [];
    if (members.length === 0) {
      console.error("❌ 沒有口試委員資料");
      return false;
    }

    const layouts = () => [...form.querySelectorAll(".advisor_layout")];
    const addButton = get('input[name="add_commtt"]', form);
    if (!addButton) return false;

    // Let the page's own handler build blocks whose fields are named the way
    // StuTempAdvisor expects; blocks left over from an earlier save are dropped.
    while (layouts().length < members.length) {
      const before = layouts().length;
      addButton.click();
      if (layouts().length === before) {
        console.error("❌ 無法新增口試委員輸入框");
        return false;
      }
    }
    layouts()
      .slice(members.length)
      .forEach(layout => layout.remove());

    // The first block is the advisor's: it is the only one whose 職稱 menu
    // offers 指導教授, so the members must stay in this order.
    layouts().forEach((layout, index) => {
      const member = members[index];
      const who = `口試委員 ${index + 1}`;
      setValue('input[name="advisor_c"]', member.nameZh, {
        root: layout,
        label: `${who} 中文姓名`
      });
      setValue('input[name="advisor_e"]', member.nameEn, {
        root: layout,
        label: `${who} 英文姓名`
      });
      setSelect('select[name="advisor_title"]', member.title, {
        root: layout,
        label: `${who} 職稱`
      });
      setValue('input[name="email"]', member.email, {
        root: layout,
        label: `${who} 電子郵件信箱`
      });
      setValue('input[name="advisor_ORCID"]', member.orcid, {
        root: layout,
        label: `${who} ORCID`
      });
    });
    return true;
  }

  function finish(reminder) {
    window.scrollTo({ top: 0, behavior: "smooth" });

    console.log("================================");
    console.log("✅ 所有欄位填寫完成");
    console.log(reminder);
    console.log("⚠️ 請檢查內容後自行按按鈕");
    console.log("================================");
  }

  if (document.querySelector('form[name="StuSubmitForm"]')) {
    console.log("🚀 開始填寫 NTU 論文資料");
    if (fillThesisPage()) finish("⚠️ 尚未按「暫存」或「下一步」");
  } else if (document.querySelector('form[name="StuTempAdvisorForm"]')) {
    console.log("🚀 開始填寫 NTU 口試委員名單");
    if (fillCommitteePage()) finish("⚠️ 尚未按「下一步」");
  } else {
    console.error("❌ 這頁不是「輸入論文資料」或「設定口試委員名單」");
  }
})();
