#!/usr/bin/env python3
"""Regenerate ntu-academic-units.tex from NTU's published lists of units.

    pixi run units

The generated file is committed, so neither the build nor the TDR generator
needs network access. Re-run this when NTU reorganises a college, which happens
every few years:

    https://www.ntu.edu.tw/academics/academics_list.html
    https://www.ntu.edu.tw/english/academics/academics_list.html

Both pages list one section per college with its departments beneath, in the
same order, so the colleges are zipped positionally into bilingual pairs; the
script refuses to write anything if their counts disagree, since that would pair
a college with the wrong English name.

The department lists are NOT zipped. The two pages disagree about a few of them
— at the time of writing the English page carries a graduate program the Chinese
one omits, and the Chinese page carries one the English one omits — so pairing
by position would silently attach the wrong translation. Each language's
departments are therefore recorded against the college of that same language,
and each field is checked against its own list.
"""

from __future__ import annotations

import html
import re
import sys
from pathlib import Path
from urllib.request import Request, urlopen

ZH_URL = "https://www.ntu.edu.tw/academics/academics_list.html"
EN_URL = "https://www.ntu.edu.tw/english/academics/academics_list.html"
OUTPUT = Path(__file__).resolve().parents[1] / "ntu-academic-units.tex"

# Colleges are h2 headings carrying the site's `searchcontent` marker class and
# departments are links carrying the same marker, both in document order.
SECTION = re.compile(
    r'<h2[^>]*class="[^"]*searchcontent[^"]*"[^>]*>(.*?)</h2>'
    r'|<a[^>]*class="searchcontent[^"]*"[^>]*>(.*?)</a>',
    re.S,
)


def fetch(url: str) -> str:
    request = Request(url, headers={"User-Agent": "ntu-thesis-template"})
    with urlopen(request, timeout=90) as response:
        return response.read().decode("utf-8", errors="ignore")


def text_of(fragment: str) -> str:
    return html.unescape(re.sub(r"<[^>]+>", "", fragment)).strip()


def parse(page: str) -> dict[str, list[str]]:
    """Map each college to its departments, preserving page order."""
    units: dict[str, list[str]] = {}
    college: str | None = None
    for match in SECTION.finditer(page):
        heading, link = match.group(1), match.group(2)
        if heading is not None:
            name = text_of(heading)
            # Each college heading is emitted twice, once per responsive layout.
            if name and name != college:
                units.setdefault(name, [])
                college = name
        elif college is not None:
            name = text_of(link)
            if name and name not in units[college]:
                units[college].append(name)
    return units


def main() -> None:
    zh = parse(fetch(ZH_URL))
    en = parse(fetch(EN_URL))

    if len(zh) != len(en):
        sys.exit(f"college counts differ: {len(zh)} Chinese, {len(en)} English")
    if not zh:
        sys.exit("no colleges found; the page markup has probably changed")

    for (zh_college, zh_depts), (en_college, en_depts) in zip(
        zh.items(), en.items()
    ):
        if len(zh_depts) != len(en_depts):
            print(
                f"note: {zh_college} lists {len(zh_depts)} units, "
                f"{en_college} lists {len(en_depts)}; "
                "each language is checked against its own list",
                file=sys.stderr,
            )

    lines = [
        "% Generated by scripts/fetch_academic_units.py; do not edit by hand.",
        "%",
        "% 臺大公布的學術單位一覽，供 ntuthesis.cls 與 generate_tdr_upload_script.py",
        "% 檢查 ntusetup.tex 的 college 與 institute 是否為正式名稱。",
        "%",
        "% NTU's published list of academic units. ntuthesis.cls warns and",
        "% generate_tdr_upload_script.py errors when ntusetup.tex names a college",
        "% or institute that is not here.",
        "%",
        "% \\ntu@declarecollege{中文}{English} pairs the two names of one college.",
        "% \\ntu@declareinstitute{學院}{系所} lists a unit under the college of the",
        "% same language, because the two pages do not list identical departments.",
        "%",
        f"% {ZH_URL}",
        f"% {EN_URL}",
        "",
    ]
    for (zh_college, zh_depts), (en_college, en_depts) in zip(
        zh.items(), en.items()
    ):
        lines.append(f"\\ntu@declarecollege{{{zh_college}}}{{{en_college}}}")
        for dept in zh_depts:
            lines.append(f"\\ntu@declareinstitute{{{zh_college}}}{{{dept}}}")
        for dept in en_depts:
            lines.append(f"\\ntu@declareinstitute{{{en_college}}}{{{dept}}}")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    total = sum(len(v) for v in zh.values())
    print(f"wrote {OUTPUT.name}: {len(zh)} colleges, {total} units")


if __name__ == "__main__":
    main()
